#!/bin/bash

packages=(
	"volumeicon-alsa"
	"xautolock"
	"unclutter"
	"neofetch"
	"vim"
	"fortune"
	"fortunes-off"
	"cowsay"
	"openbox"
	"pcmanfm"
	"conky"
	"sakura"
	"tint2"
	"compton"
	"xorg"
	"i3lock"
	"dmenu"
	"feh"
	"network-manager"
	"pavucontrol"
	"scrot"
	"imagemagick"
	"hibernate"
	"libnotify-bin"
	"network-manager-gnome"
)

sudo apt update

sudo apt install $(echo "${packages[*]}")

./configure
