#!/bin/bash

packages=(
	"volumeicon-alsa"
	"xautolock"
	"unclutter"
	"neofetch"
	"vim"
	"fortune"
	"fortunes-off"
	"cowsay"
	"openbox"
	"pcmanfm"
	"conky"
	"sakura"
	"tint2"
	"compton"
	"xorg"
	"i3lock"
	"dmenu"
	"feh"
	"network-manager"
	"pavucontrol"
	"scrot"
	"imagemagick"
	"hibernate"
	"libnotify-bin"
	"network-manager-gnome"
	"pulsemixer"
	"texlive-latex-recommended"
	"texlive-latex-extra"3
	"texlive-fonts-extra"
	"texlive-extra-utils"
	"zathura"
	"latexmk"
	"libx11-dev"
	"libxinerama-dev"
	"libxft-dev"
	"xclip"
	"speedtest-cli"
	"rsync"
	"wmctrl"
	"resolvconf"
)

sudo apt update

sudo apt install $(echo "${packages[*]}")

./configure
